name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Deploy the html to pages ..."
          echo "${{ github.ref }}"
          
